### ISSUE TITLE
ECH website update July 2022

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#401]
Below is the list of Issues resolved, page updated:

- [x] [Issue 55](https://github.com/ethereum-cat-herders/ech-website-v2/issues/55) - Update page for Gray Glacier
- [x] [Issue 52](https://github.com/ethereum-cat-herders/ech-website-v2/issues/52) - Update EIP Resources for EIP-3540
- [x] [Issue 53](https://github.com/ethereum-cat-herders/ech-website-v2/issues/53) - Create EIP Resources for EIP-3670
- [x] [Issue 22](https://github.com/ethereum-cat-herders/ech-website-v2/issues/22) - Page layout change - EIP Resources 
- [x] [Issue 16](https://github.com/ethereum-cat-herders/ech-website-v2/issues/16) Customized - We'll be back soon page

Total Hours: 8 hrs.
Amount = 55 * 8 = 440 USD = 440/1681 = 0.261748
Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="877" alt="image" src="https://user-images.githubusercontent.com/97191248/188222907-797e0eb2-548d-4556-ab7a-9531e6f8e715.png">

**Comment by poojaranjan** [comment]
Multisig tx 255; tx completed!
