### ISSUE TITLE
ECH website update Aug 2022

### ISSUE THREAD

**Issue by EtherWorldCo** [ethereum-cat-herders/funding#402]
Below is the list of Issues resolved, page updated:

- [x] [Issue 18](https://github.com/ethereum-cat-herders/ech-website-v2/issues/18) - Auto-update of meetings recordings on home page
- [x] [Issue 51](https://github.com/ethereum-cat-herders/ech-website-v2/issues/51) - Add ECH Podcast To ECH website
- [x] [Issue 54](https://github.com/ethereum-cat-herders/ech-website-v2/issues/54) - Update page for Arrow Glacier
- [x] [Issue 58](https://github.com/ethereum-cat-herders/ech-website-v2/issues/58) - Update page for The Merge
- [x] [Issue 61](https://github.com/ethereum-cat-herders/ech-website-v2/issues/61) - Card for Altair Upgrade
- [x] Changed logic for meetings on home page
- [x] Fixed the routes for website deployment

Total Hours: 11 hrs.
Amount = 55 * 11 = 605 USD = 605/ 1553 = 0.3895685 ETH
Wallet: 0x580F4c272174eAAc1523a676cD33d4CC3ED15718

<img width="876" alt="image" src="https://user-images.githubusercontent.com/97191248/188223504-5a1939a6-0924-4ac8-8c98-6b408aad36fd.png">

**Comment by poojaranjan** [comment]
Multisig tx 255; tx completed!
